meta_product_name: "Flatcares"
meta_title: "Flatcares - Make your house trully collaborative"
meta_description: "Spread responsabilities, communicate with your buddies and get all expenses under control."
meta_image: "meta_image.jpg" # should exist in `app/assets/images/`

